### ISSUE TITLE
cdk ls not working

### ISSUE THREAD

**Issue by thomasklinger1234** [kindlyops/bazel-cdk-demo#466]
Hey, 

first: thanks for this wonderful demo! 

When running `bazel run cdk -- ls` I get the following error: 

```
bazel-cdk-demo [master] % bazel run cdk -- ls

INFO: Analyzed target //:cdk (608 packages loaded, 16832 targets configured).
INFO: Found 1 target...
Target //:cdk up-to-date:
  dist/bin/cdk.sh
  dist/bin/cdk_loader.js
  dist/bin/cdk_require_patch.js
INFO: Elapsed time: 27.175s, Critical Path: 5.73s
INFO: 1 process: 1 local.
INFO: Build completed successfully, 19 total actions
INFO: Build completed successfully, 19 total actions
Error: Cannot find module 'com_kindlyops_bazel_cdk_demo/lib/app.js'
Require stack:
-
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Object.<anonymous> (/private/var/tmp/_bazel_tklinger/ddc144967cbb78a5f9c819c1caa0dd87/execroot/com_kindlyops_bazel_cdk_demo/bazel-out/darwin-fastbuild/bin/lib/app_loader.js:32:24)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
Subprocess exited with error 1
```

This happens on a fresh checkout of the master branch. Do I need to change something or is `cdk ls` not yet working?

**Comment by statik** [comment]
@thomasklinger1234 sorry for the delay. looks like this has bitrotted, I will try to take a look soon. I will need to work through some dependency updates in order to get back to a working state.

**Comment by statik** [comment]
@thomasklinger1234 I think this is fixed now! when you get a chance, I'd love to know whether it works for you.

**Comment by thomasklinger1234** [comment]
I have tried it and it works. Fantastic, thank you very much @statik :)
